# SERVER ENGINE & TERMINAL STATE                                      #
set -g default-terminal "screen"
set -g history-limit 50000
set -s set-clipboard on
set -g allow-passthrough on

# Faster modal key responsiveness (Overriding sensible's default 10ms)
set -s escape-time 0

# Window / Pane Base Indexing (1-based for keyboard ergonomics)
set -g base-index 1
setw -g pane-base-index 1

# Environmental Constraints
set -g mouse on
set -g focus-events off
setw -g aggressive-resize off
setw -g clock-mode-style 12
set -g renumber-windows on
set-option -g allow-rename off
set -g detach-on-destroy off

# Mode Keys (Enforce strict vi-emulation inside buffers)
set -g status-keys vi
set -g mode-keys vi

# Session Lifecycle Management
bind -n C-r     command-prompt -I '#S' 'rename-session -- "%%"'
bind -n C-n command-prompt -p "New Session:" "new-session -A -s '%%'"
bind -n C-x     confirm-before -p "kill session #S? (y/n)" "kill-session"

# Window Navigation & Allocation
bind -n M-r     command-prompt -I '#W' 'rename-window "%%"'
bind -n M-n     new-window
bind -n M-x     kill-pane

# Layout & Pane Splits (Alt-v / Alt-h)
bind -n M-v     split-window -h
bind -n M-h     split-window -v

# Client State & Tree Management
bind -n M-q     detach-client

# VI COPY-MODE & BUFFER SELECTION                                      #
bind -n M-y copy-mode
bind -T copy-mode-vi v   send-keys -X begin-selection
bind -T copy-mode-vi y   send-keys -X copy-pipe-and-cancel
bind -T copy-mode-vi M-y send-keys -X cancel

# Move current window left with prefix + h
bind-key h swap-window -t -1\; select-window -t -1

# Move current window right with prefix + l
bind-key l swap-window -t +1\; select-window -t +1

# Theming
set-option -g status-position top
set -g status-right-style 'fg=white bg=default'
set -g status-right "  #[fg=red]#(grep -E '^NAME=' /etc/os-release | cut -d= -f2 | tr -d '\"') #[fg=brightblack]// #[fg=green]#(free -h | awk '/Mem:/ {print $3\"/\"$2}') #[fg=brightblack]// #[fg=cyan]%H:%M:%S  %A, %d/%m #[fg=brightblack]// #[fg=yellow]BAT #(cat /sys/class/power_supply/BAT0/capacity) ⚡"
set -g status-right-length 200

set -g status-left " #[fg=cyan,bold]#S #[fg=brightblack]// #[fg=magenta] #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'no-git') #[fg=brightblack]// "
set -g status-left-length 0

set -g status-justify left
set -g status-style 'bg=default'

setw -g window-status-style 'fg=black bg=blue'
setw -g window-status-format ' #I #[fg=black]#W #[fg=blue]#F '

setw -g window-status-current-format "#[fg=black,bg=yellow] #I #[fg=black,bg=blue,bold] #W #[default]"
setw -g window-status-format "#[fg=white,bg=brightblack] #I #[fg=white,bg=black] #W #[default]"

# 1. Force tmux to use its proper inner terminal protocol
set -g default-terminal "tmux-256color"

# 2. Tell tmux that outer terminal supports TrueColor (RGB/Tc)
set -as terminal-features ",st-256color:RGB"
set -as terminal-overrides ",st-256color:Tc"
